### ISSUE TITLE
Kicked out after a few minutes on 2.4

### ISSUE THREAD

**Issue by superarts** [Sunblood/D2RML#12]
Is anyone seeing the same issue? My accounts got kicked out after 1 or 2 min while multiboxing. F blizzard

**Comment by hc4fun** [comment]
I notice that in 2.4 I have lots of crashes, b4 I have it maby few times totally, now its more often, I didn't change anything but w/o any reason game crashes and I have to open it again.
From time to time its that I open one instance and then next one crash and I have to reopen it again...

I'm open 3 copy of d2r at once.

**Comment by superarts** [comment]
My current conclusion is that it is due to resource usage. Please check my post here for details: https://www.reddit.com/r/Diablo/comments/ui7z5b/multiboxing_d2r_24_playing_now/
