### ISSUE TITLE
\Battle.net.exe

### ISSUE THREAD

**Issue by deepfire** [Sunblood/D2RML#5]
When I click `Add token`, then enter the identifier and region -- an error pops up, about inability to find `\Battle.net.exe`.

I don't have Battle.net installed in a default `Program Files` location -- perhaps that's the problem?

In addition, after this error popup, the D2RML hardlocks and refuses to exit.  Starting D2R makes it exit, though.

**Comment by Sunblood** [comment]
Bnet install dir is read from registry at HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Battle.net key InstallLocation
