### ISSUE TITLE
May you add the support to MOD in future release?

### ISSUE THREAD

**Issue by chess0n** [Sunblood/D2RML#7]
Thanks for your nice job, it even works on my laptop(HP EliteBook 830 G7) with an intel  integrated graphics card. And  I will to use third part MOD on D2RML, do you consider the request in future?
By the way, the Batttle.net APP now support the feature.
![Screenshot 2021-11-17 160309](https://user-images.githubusercontent.com/45847917/142159945-5c483b23-8bc5-4ca8-9e2b-ee923392bedd.png)

**Comment by Sunblood** [comment]
You can do this with the "Game cmdline" option in D2RML. Just put the same -mod X line in there and check the box.
